MYSQL_IMAGE := mysql
MYSQL_DATABASE := project-db
MYSQL_USERNAME := root
MYSQL_ROOT_PASSWORD := Nepal@123
MYSQL_ALLOW_EMPTY_PASSWORD := no

mysql:
	docker run -d -it -v $(pwd)/db_data:/var/lib/mysql --name mysql -p 3306:3306 -e MYSQL_DATABASE=${MYSQL_DATABASE} -e MYSQL_USERNAME=${MYSQL_USERNAME} -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} -e MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD} ${MYSQL_IMAGE}
